version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=app
    - POSTGRES_PASSWORD=app
    - POSTGRES_DB=db
    ports:
    - 5432:5432
    volumes:
    - ./data:/var/lib/postgresql
  app:
    build: .
    command: sh -c "npx prisma migrate dev && npm run dev"
    ports:
    - 3000:3000
    volumes:
    - ./:/app
    links:
    - postgres:postgres
    depends_on:
    - postgres
    image: nodeimage