version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=app
    - POSTGRES_PASSWORD=app
    - POSTGRES_DB=db
    ports:
    - 5432:5432
    volumes:
    - ./data:/var/lib/postgresql
  app:
    build: .
    command: sh -c "npx prisma migrate dev"
    volumes:
      - ./:/app
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://app:app@postgres:5432/db
    depends_on:
    - postgres