version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=app
    - POSTGRES_PASSWORD=app
    - POSTGRES_DB=db
    ports:
    - 5432:5432
    volumes:
    - ./data:/var/lib/postgresql
  app:
    depends_on:
      - postgres
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://app:app@postgres:5432/db
   