import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const attachmentsQuery = api.example.getStock.useQuery();
  const attachments = attachmentsQuery.data;
  const stock =
    attachments?.stockCount || attachments?.stockCount === 0
      ? attachments?.stockCount
      : "Create Data";

  const { mutate } = api.example.increment.useMutation({
    onSuccess: async () => {
      await attachmentsQuery.refetch();
    },
  });

  return (
    <>
      <Head>
        <title>Morpher Challenge</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-10 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-2xl font-semibold text-white">
          Stock Number: {stock}
        </h1>
        <button
          onClick={() => mutate()}
          className="rounded-lg bg-slate-400 px-5 py-1.5 font-semibold text-slate-800"
        >
          Increment
        </button>
      </main>
    </>
  );
};

export default Home;
